### ISSUE TITLE
Unicode: ordinal not in range(128)

### ISSUE THREAD

**Issue by colindaven** [mdshw5/pyfaidx#104]
`
pip3 install https://github.com/mdshw5/pyfaidx/zipball/master

Collecting https://github.com/mdshw5/pyfaidx/zipball/master
  Downloading https://github.com/mdshw5/pyfaidx/zipball/master
     | 71kB 183kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/scratch/global/pip-b9qlqbwo-build/setup.py", line 26, in <module>
        long_description=open('README.rst').read(),
      File "/home/bioinformatics/programs/venv_mikado/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16813: ordinal not in range(128)

`

**Comment by mdshw5** [comment]
Sorry about this - it was an issue already fixed in #101. I've merged the changes and will release a bug-fix version this afternoon.
