### ISSUE TITLE
UnicodeDecodeError while reading file: how to explicit decode format?

### ISSUE THREAD

**Issue by LucaCappelletti94** [mdshw5/pyfaidx#146]
Hello, I wanted to parse a fasta file but I cannot seem able to identify a way to pass to the `Fasta` class a decode format. How can I proceed? Thanks!
```py
Traceback (most recent call last):
  File "fasta_editor.py", line 7, in <module>
    for i, gene in genes:
  File "/home/cappelletti/code/.virtualenvs/virtual-py36gpu/lib/python3.6/site-packages/pyfaidx/__init__.py", line 822, in __iter__
    yield self[start:end]
  File "/home/cappelletti/code/.virtualenvs/virtual-py36gpu/lib/python3.6/site-packages/pyfaidx/__init__.py", line 806, in __getitem__
    return self._fa.get_seq(self.name, start + 1, stop)[::step]
  File "/home/cappelletti/code/.virtualenvs/virtual-py36gpu/lib/python3.6/site-packages/pyfaidx/__init__.py", line 1032, in get_seq
    seq = self.faidx.fetch(name, start, end)
  File "/home/cappelletti/code/.virtualenvs/virtual-py36gpu/lib/python3.6/site-packages/pyfaidx/__init__.py", line 624, in fetch
    seq = self.from_file(name, start, end)
  File "/home/cappelletti/code/.virtualenvs/virtual-py36gpu/lib/python3.6/site-packages/pyfaidx/__init__.py", line 676, in from_file
    seq = self.file.read(seq_blen).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 6: invalid continuation byte
```
You can get the fasta file at fault by running the following, but be warned, once extracted is about 60GB:
```{bash}
wget ftp://ftp.ensembl.org/pub/release-94/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.toplevel.fa.gz
```
My code is just the following:

```py
from pyfaidx import Fasta

path = "Homo_sapiens.GRCh38.dna.toplevel.fa"
genes = Fasta(path)

for i, gene in genes:
    if i > 2:
        break
    print(gene)
```

**Comment by mdshw5** [comment]
I’ll try to reproduce this and let you know what I fine. Thanks!

**Comment by LucaCappelletti94** [comment]
Somehow how the same code works on the very same file, so I believe it was fault to some other variable. Sorry for eventually having wasted your time.

**Comment by mdshw5** [comment]
No problem. These things happen. Probably during download some character corrupted and was not in the ASCII set. Glad you sorted it out!
