### ISSUE TITLE
Q: number of keys == number of headers?

### ISSUE THREAD

**Issue by ChillarAnand** [mdshw5/pyfaidx#75]
I have downloaded [this fasta file](http://www.lncipedia.org/downloads/lncipedia_3_1.fasta) and it has 111685 headers in it.

```
$ grep '>' ref.fasta | wc -l
111685
```

But when I pass this to pyfaidx, it is showing only 22144 keys?

```
In [10]: from pyfaidx import Fasta

In [11]: data = Fasta('ref.fasta')

In [12]: len(data.keys())
Out[12]: 22144
```

**Comment by mdshw5** [comment]
Hi @ChillarAnand. Thanks for reporting an issue. I'm actually able to reproduce the issue, but fortunately this seems to be an issue with the "lncipedia" FASTA formatting:

```python
>>> from pyfaidx import Fasta
>>> data = Fasta('/tmp/lncipedia_3_1.fasta')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyfaidx/__init__.py", line 590, in __init__
    sequence_always_upper=sequence_always_upper)
  File "pyfaidx/__init__.py", line 240, in __init__
    self.build_index()
  File "pyfaidx/__init__.py", line 323, in build_index
    rname = line.rstrip()[1:].split()[0]
IndexError: list index out of range
>>> data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'data' is not defined
>>> data = Fasta('/tmp/lncipedia_3_1.fasta')
>>> data
Fasta("/tmp/lncipedia_3_1.fasta")
>>> len(data.keys())
22144
>>> from pyfaidx import __version__
>>> __version__
'0.4.2'
```

I've added a new case for raising a `FastaIndexingError` and this now shows the line number where the problematic sequence occurs:

```python
>>> from pyfaidx import Fasta
>>> data = Fasta('/tmp/lncipedia_3_1.fasta')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyfaidx/__init__.py", line 607, in __init__
    sequence_always_upper=sequence_always_upper)
  File "pyfaidx/__init__.py", line 253, in __init__
    raise FastaIndexingError(e)
pyfaidx.FastaIndexingError: Bad sequence name > at line 408775.
>>> 
```

I'll release this new feature with v0.4.3. In the mean time I recommend removing any sequences with "blank" names from your FASTA file before using it with any tools.

**Comment by ChillarAnand** [comment]
Thanks :)
