### ISSUE TITLE
Value Error when loading Fasta File

### ISSUE THREAD

**Issue by darencard** [mdshw5/pyfaidx#88]
I've incorporated pyfaidx successfully into a script I'm using to extract sequences from a reference genome. It has worked fine on a couple genomes, but I'm having an issue with the last one I am working with. Within the script, I'm loading the Fasta genome using the following command:
```
scaff = Fasta(options.reference, one_based_attributes=True)
```
where `options.reference` is being read from the command-line options.

The error I receive is:
```
Traceback (most recent call last):
  File "create_CDS.py", line 153, in <module>
    scaff = Fasta(options.reference, one_based_attributes=True)
  File "/Library/Python/2.7/site-packages/pyfaidx/__init__.py", line 590, in __init__
    sequence_always_upper=sequence_always_upper)
  File "/Library/Python/2.7/site-packages/pyfaidx/__init__.py", line 237, in __init__
    self.read_fai(split_char)
  File "/Library/Python/2.7/site-packages/pyfaidx/__init__.py", line 264, in read_fai
    rname, rlen, offset, lenc, lenb = line.split('\t')
ValueError: need more than 3 values to unpack
```

The header and first line of wrapped nucleotide sequence for a few scaffolds look like this:
```
>NW_006532014.1 Python bivittatus unplaced genomic scaffold, Python_molurus_bivittatus-5.0.2 Scaffold0, whole genome shotgun sequence
aggcctggcgcaatatggttcatggggtcacgaagagtcggacacgacttaacgactaaacaacaattaaTTCTAAACCC
>NW_006532015.1 Python bivittatus unplaced genomic scaffold, Python_molurus_bivittatus-5.0.2 Scaffold1, whole genome shotgun sequence
ggcttcactgagttacgcaagcccctttgccacgacaaggcagtgatccatgaaggggaaagggAACACTTAAGGTCGAT
>NW_006532016.1 Python bivittatus unplaced genomic scaffold, Python_molurus_bivittatus-5.0.2 Scaffold2, whole genome shotgun sequence
aggaaggcctggcgcaatatggttcatggggtcacgaagagtcggacacgacttaacgactaaacaacaacaacaaaaac
```

As I've said, this has worked fine with two other genomes (all are from NCBI), which have sequence lines that looks like this:
```
>NW_013657680.1 Thamnophis sirtalis isolate EDBJR-23777 unplaced genomic scaffold, Thamnophis_sirtalis-6.0 Scaffold0, whole genome shotgun sequence
tattgtattgtattgtattgtattgtattgtattgtattgtattgtattgtatgttatAGACAAGAAAAACCTTATGAGT
>NW_013657681.1 Thamnophis sirtalis isolate EDBJR-23777 unplaced genomic scaffold, Thamnophis_sirtalis-6.0 Scaffold1, whole genome shotgun sequence
TTGGCCTGCTACACTtgctattattctactatgcatttttttcttgtgggaaaatgggaggggggattgtactgAGTTAG
>NW_013657682.1 Thamnophis sirtalis isolate EDBJR-23777 unplaced genomic scaffold, Thamnophis_sirtalis-6.0 Scaffold2, whole genome shotgun sequence
tatatatatatatatatatatatatatatatatatatatacataaacggcatcttttttttccttccctttagaaattaa
```
and...
```
>AZIM01000001.1 Ophiophagus hannah scaffold1.1, whole genome shotgun sequence
gcggcatataaatgtgaataaaaaaaaacttttgcccATATTATAAGGACCACCATAAGAAGCCAACCTTGAATATCTTA
>AZIM01000002.1 Ophiophagus hannah scaffold2.1, whole genome shotgun sequence
tttttcttatatgtatccattttatgtattcataactatgtttaNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
>AZIM01000003.1 Ophiophagus hannah scaffold3.1, whole genome shotgun sequence
aacaaccggttctagagaataggtgcgaataggtagaatcccacccctgataattaTGTCTTGGAGGAATAGTCACAATT
```

I don't see any obvious differences between the files, but maybe you do (or there is a problem somewhere else in the file that is causing the error). Any guidance you have would be greatly appreciated.

Best,
Daren

**Comment by mdshw5** [comment]
Hi @darencard. Thanks for filing an issue. My first guess would be that the index file is malformed. Is this a FASTA index that came with the FASTA download? If so, I would try deleting it and allowing pyfaidx to re-index the file. If that fails, then there is something in the file that is preventing pyfaidx from completing the index generation. If this is public data, could you post the link?

**Comment by darencard** [comment]
@mdshw5 That indeed solved the issue. Thanks for the prompt reply and for producing such a useful package!
