### ISSUE TITLE
Faidx.file is not immediately closed if Faidx.__init__ fails when reading/building the index

### ISSUE THREAD

**Issue by dhauge** [mdshw5/pyfaidx#96]
At the end of 'Faidx.**init**', if an exception occurs in the call to 'build_index', the opened 'self.file' is not closed as control leaves the constructor. This is probably typically not a problem because the file will be closed eventually, but it was causing the 'test_feature_indexing.py' test to fail when I was running it under 'pypy' because too many files were opened. I got the following errors (the original 'IOError' because of too many files is hidden by the new 'IOError' created at line 415

```
======================================================================
ERROR: Makes all full-length lines blank and checks that error is raised
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hauge/dev/tools/pyfaidx/tests/test_feature_indexing.py", line 158, in test_valgrind_blank_lines
    Faidx(name)
  File "/Users/hauge/dev/tools/pyfaidx/.tox/pypy/site-packages/pyfaidx/__init__.py", line 311, in __init__
    self.build_index()
  File "/Users/hauge/dev/tools/pyfaidx/.tox/pypy/site-packages/pyfaidx/__init__.py", line 416, in build_index
    raise IOError("%s may not be writable. Please use Fasta(rebuild=False), Faidx(rebuild=False) or faidx --no-rebuild." % self.indexname)
IOError: /var/folders/pj/fc6s3hmd15ddfljvmr2rqzfw0000gn/T/tmps2Ppc3.fai may not be writable. Please use Fasta(rebuild=False), Faidx(rebuild=False) or faidx --no-rebuild.
```

The fix is trivial, and I'll submit a pull request for it shortly, but it basically involves modifying the exception handling in the '**init**' method to close the file:

``` python
        try:
            if os.path.exists(self.indexname) and getmtime(self.indexname) >= getmtime(self.filename):
                self.read_fai(split_char)
            elif os.path.exists(self.indexname) and getmtime(self.indexname) < getmtime(self.filename) and not rebuild:
                self.read_fai(split_char)
                warnings.warn("Index file {0} is older than FASTA file {1}.".format(self.indexname, self.filename), RuntimeWarning)
            else:
                self.build_index()
                self.read_fai(split_char)
        except FastaIndexingError as e:
            os.remove(self.indexname)
            self.file.close()
            raise FastaIndexingError(e)
        except Exception:
            # Handle potential exceptions other than 'FastaIndexingError'
            self.file.close()
            raise
        finally:
            self.lock.release()
```

**Comment by dhauge** [comment]
On a related note, I'm using Tox to run the tests locally on all environments (seemed easier than trying to run them via Travis). Would you be interested in the tox.ini I was using (also includes some coverage configuration changes to combine results across test environments)?

**Comment by mdshw5** [comment]
Yes please. I started using tox for some other projects and like the idea. Thanks for all your effort here.
